"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["Type Proofing.py"]
DATA_FILES = [
    "config.py",
    "prooftexts.py",
    "proof_generation.py",
    "font_analysis.py",
    "ui_interface.py",
    "AdobeBlank.otf",
]
OPTIONS = {
    "packages": [
        "drawBot",
        "drawBotGrid",
        "wordsiv",
        "fontTools",
        "vanilla",
    ],
    "iconfile": "TypeProofing.icns",
    # Add descriptions for folder access permissions
    "plist": {
        "CFBundleIdentifier": "com.dogray.typeproofing",
        "CFBundleName": "Type Proofing",
        "CFBundleDisplayName": "Type Proofing",
        "NSAppleEventsUsageDescription": "This app needs access to Apple Events for file operations.",
        "NSDocumentsFolderUsageDescription": "This app needs access to Documents folder to save proof files.",
        "NSDesktopFolderUsageDescription": "This app needs access to Desktop folder to save proof files.",
        "NSDownloadsFolderUsageDescription": "This app needs access to Downloads folder to save proof files.",
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=[
        "py2app",
        "drawbot",
        "drawbotgrid",
        "wordsiv",
        "fonttools",
        "cocoa-vanilla",
        "pyobjc",
        "jaraco.text",
    ],
)
