"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["Type Proofing.py"]
DATA_FILES = [
    "config.py",
    "prooftexts.py",
    "proof_generation.py",
    "font_analysis.py",
    "ui_interface.py",
    "AdobeBlank.otf",
]
OPTIONS = {
    "packages": [
        "drawBot",
        "drawBotGrid",
        "wordsiv",
        "fontTools",
        "vanilla",
    ],
    "iconfile": "TypeProofing.icns",
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=[
        "py2app",
        "drawbot",
        "drawbotgrid",
        "wordsiv",
        "fonttools",
        "cocoa-vanilla",
        "pyobjc",
        "jaraco.text",
    ],
)
