"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

NAME = "TypeProofing"
VERSION = "1.6.0"
APP = ["TypeProofing.py"]
DATA_FILES = [
    "accented_dictionary.py",
    "AdobeBlank.otf",
    "app.py",
    "config.py",
    "fonts.py",
    "pdf_manager.py",
    "proof.py",
    "sample_texts.py",
    "script_texts.py",
    "settings.py",
    "setup.py",
    "TypeProofing.py",
    "ui.py",
]
OPTIONS = {
    "packages": [
        "drawBot",
        "drawBotGrid",
        "wordsiv",
        "fontTools",
        "vanilla",
    ],
    "iconfile": "TypeProofing.icns",
    "compressed": True,
    "excludes": [
        "setuptools",
        "pkg_resources",
        "tkinter",
        "turtle",
    ],
    # Add descriptions for folder access permissions
    "plist": {
        "CFBundleName": NAME,
        "CFBundleShortVersionString": VERSION,
        "CFBundleGetInfoString": " ".join([NAME, VERSION]),
        "CFBundleExecutable": NAME,
        "CFBundleIdentifier": "com.dograytype.typeproofing",
        "CFBundleDisplayName": NAME,
        "NSAppleEventsUsageDescription": (
            "This app needs access to Apple Events for file operations."
        ),
        "NSDocumentsFolderUsageDescription": (
            "This app needs access to Documents folder to save proof files."
        ),
        "NSDesktopFolderUsageDescription": (
            "This app needs access to Desktop folder to save proof files."
        ),
        "NSDownloadsFolderUsageDescription": (
            "This app needs access to Downloads folder to save proof files."
        ),
        # Disable automatic state restoration to eliminate secure coding warning
        "NSApplicationSupportsSecureRestorableState": False,
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=[
        "py2app",
        "drawbot",
        "drawbotgrid",
        "wordsiv",
        "fonttools",
        "cocoa-vanilla",
        "pyobjc",
        "jaraco.text",
    ],
)
