#ifndef TPNATIVE_H
#define TPNATIVE_H

/* This file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
typedef struct WordSiv WordSiv;

typedef struct TPFontInfo {
  char *family_name;
  char *subfamily_name;
  uint16_t weight;
  uint16_t width;
  uint16_t fs_selection;
  bool is_variable;
  double slant;
  double optical_size;
  char *axes_json;
  char *features_json;
} TPFontInfo;

WordSiv *wsv_create(uint64_t seed);

void wsv_free(WordSiv *ptr);

void wsv_free_string(char *ptr);

char *wsv_text(WordSiv *ptr,
               const char *glyphs,
               uint32_t n_paras,
               double numbers,
               double rnd_punc,
               const char *para_sep,
               const char *vocab);

char *wsv_words(WordSiv *ptr,
                const char *glyphs,
                const char *case_str,
                const char *contains,
                uint32_t n_words,
                uint32_t min_wl,
                uint32_t max_wl,
                const char *vocab,
                const char *startswith,
                const char *endswith,
                const char *inner);

char *wsv_top_word(WordSiv *ptr,
                   const char *glyphs,
                   const char *case_str,
                   const char *regexp,
                   uint32_t idx,
                   uint32_t min_wl,
                   const char *vocab);

void wsv_seed(WordSiv *ptr, uint64_t seed);

struct TPFontInfo *tp_load_font(const uint8_t *data, uintptr_t len);

void tp_free_font_info(struct TPFontInfo *ptr);

char *tp_get_charset(const uint8_t *data, uintptr_t len);

char *tp_get_axes_json(const uint8_t *data, uintptr_t len);

char *tp_get_named_instances_json(const uint8_t *data, uintptr_t len);

char *tp_get_substitutions_json(const uint8_t *data, uintptr_t len);

const char *tp_version(void);

#endif  /* TPNATIVE_H */
